CLUSTER_UTILIZATION = "cluster_utilization"
SYSTEM_UTILIZATION = "system_utilization"
USED = "used"
TOTAL = "total"
PERCENT_USED = "percent_used"
STATUS_UP = "up"
STATUS_NOT_MONITORED = "not_monitored"
STATUS_DOWN = "down"
